[features]
seeds = true
skip-lint = false

[programs.localnet]
defighter = "HGkRbNawHR3PbA2h1LgqtMNCj6jcrS14c86wDUvS3dTL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
build = "anchor build"
deploy = "anchor deploy"


