[features]
seeds = true
skip-lint = false

# Optional: keep localnet mapping if you ever run a local validator
# [programs.localnet]
# defighter = "YourLocalProgramIdHere"

# ✅ Add this block so Anchor knows your program id on devnet
[programs.devnet]
defighter = "HGkRbNawHR3PbA2h1LgqtMNCj6jcrS14c86wDUvS3dTL"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
build = "anchor build"
deploy = "anchor deploy"
